framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    form: {}
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

when@prod:
    framework:
        trusted_proxies: 'PRIVATE_SUBNETS'
        trusted_headers: ['x-forwarded-for', 'x-forwarded-port', 'x-forwarded-proto', 'x-forwarded-host']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
